repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.11
  hooks:
    - id: ruff-check # Run the linter
      args: [ --fix ]
      types_or: [ python, pyi, jupyter ]
    - id: ruff-format # Run the formatter
      types_or: [ python, pyi, jupyter ]
- repo: local
  hooks:
    - id: ty
      name: ty type check
      entry: uvx ty check ./src/
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
